// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClBe7iku9tz8lqpf9GXkODDNhBwuXZPeE',
    appId: '1:210900255490:web:35c5192da8a7551b75781b',
    messagingSenderId: '210900255490',
    projectId: 'rentavehicle-7c66e',
    authDomain: 'rentavehicle-7c66e.firebaseapp.com',
    storageBucket: 'rentavehicle-7c66e.firebasestorage.app',
    measurementId: 'G-50BS8PKH1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBid6UItLKwkR5IWKbuzkatUQHO0qQkLpk',
    appId: '1:210900255490:android:1a595b98696bb3a275781b',
    messagingSenderId: '210900255490',
    projectId: 'rentavehicle-7c66e',
    storageBucket: 'rentavehicle-7c66e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1FhJThFpyBePSpouJs3OIKpWonCWjzww',
    appId: '1:210900255490:ios:224b0007e1ef39b575781b',
    messagingSenderId: '210900255490',
    projectId: 'rentavehicle-7c66e',
    storageBucket: 'rentavehicle-7c66e.firebasestorage.app',
    iosClientId: '210900255490-c6fl5h6lm2l70utos3jmoh8jqf72e4o2.apps.googleusercontent.com',
    iosBundleId: 'com.rentavehicle.apps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1FhJThFpyBePSpouJs3OIKpWonCWjzww',
    appId: '1:210900255490:ios:224b0007e1ef39b575781b',
    messagingSenderId: '210900255490',
    projectId: 'rentavehicle-7c66e',
    storageBucket: 'rentavehicle-7c66e.firebasestorage.app',
    iosClientId: '210900255490-c6fl5h6lm2l70utos3jmoh8jqf72e4o2.apps.googleusercontent.com',
    iosBundleId: 'com.rentavehicle.apps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClBe7iku9tz8lqpf9GXkODDNhBwuXZPeE',
    appId: '1:210900255490:web:8ca480402fe9382e75781b',
    messagingSenderId: '210900255490',
    projectId: 'rentavehicle-7c66e',
    authDomain: 'rentavehicle-7c66e.firebaseapp.com',
    storageBucket: 'rentavehicle-7c66e.firebasestorage.app',
    measurementId: 'G-ZWZ6QXBK2V',
  );
}
